/**
 * Services Data by Category
 * All service offerings organized by category
 */

export const servicesData = {
  1: {
    // Repair (AC & Appliances)
    categoryName: 'AC Service and Repair',
    description: 'Pro service to fix your broken AC',
    services: [
      {
        id: 'ac-foam-jet',
        name: 'Foam-jet AC service',
        description: 'Dust-free filters & better airflow',
        price: 599,
        duration: '45 mins',
        rating: 4.77,
        reviews: '1.8M',
        discount: 'UP TO 17%',
        tags: [
          'Applicable for both window & split ACs',
          'Indoor and deep cleaning with foam & jet spray',
        ],
        image: '/assets/ac.png',
        badge: null,
      },
      {
        id: 'ac-lite',
        name: 'Lite AC service',
        description: 'Basic AC cleaning and maintenance',
        price: 399,
        duration: '30 mins',
        rating: 4.72,
        reviews: '2.8M',
        discount: null,
        tags: [
          'Applicable for both window & split ACs',
          'Basic filter cleaning',
        ],
        image: '/assets/ac.png',
        badge: null,
      },
      {
        id: 'ac-install-cooling',
        name: 'AC Ins/no cooling',
        description: 'Installation and cooling issues',
        price: 299,
        duration: '60 mins',
        rating: 4.78,
        reviews: '4.7M',
        discount: null,
        tags: [],
        image: '/assets/ac.png',
        badge: '₹30,000 OFF',
      },
      {
        id: 'ac-power-issue',
        name: 'AC power issue repair',
        description: 'Fix power and electrical problems',
        price: 299,
        duration: '45 mins',
        rating: 4.71,
        reviews: '1.2M',
        discount: null,
        tags: [],
        image: '/assets/ac.png',
        badge: '₹30,000 OFF',
      },
      {
        id: 'ac-noise-smell',
        name: 'AC noise/smell repair',
        description: 'Fix unusual noise and bad smell',
        price: 499,
        duration: '45 mins',
        rating: 4.78,
        reviews: '5M',
        discount: null,
        tags: [],
        image: '/assets/ac.png',
        badge: 'MOST & DOOR-BL',
      },
      {
        id: 'ac-water-leakage',
        name: 'AC water leakage repair',
        description: 'Fix water dripping issues',
        price: 299,
        duration: '40 mins',
        rating: 4.71,
        reviews: '1.7M',
        discount: null,
        tags: [],
        image: '/assets/ac.png',
        badge: 'WATER LEAKAGE',
      },
      {
        id: 'gas-refill',
        name: 'Gas refill & check-up',
        description: 'Complete gas refilling service',
        price: 2500,
        duration: '2 hrs 30 mins',
        rating: 4.75,
        reviews: '1.9M',
        discount: null,
        tags: [],
        image: '/assets/ac.png',
        badge: null,
      },
      {
        id: 'split-ac-installation',
        name: 'Split AC Installation',
        description: 'Professional split AC installation',
        price: 799,
        duration: '2 hrs',
        rating: 4.89,
        reviews: '1.5M',
        discount: null,
        tags: ['21 visits'],
        image: '/assets/ac.png',
        badge: null,
      },
      {
        id: 'window-ac-installation',
        name: 'Window AC Installation',
        description: 'Expert window AC installation',
        price: 299,
        duration: '2 hrs',
        rating: 4.82,
        reviews: '1.7M',
        discount: null,
        tags: [],
        image: '/assets/ac.png',
        badge: null,
      },
      {
        id: 'split-ac-uninstallation',
        name: 'Split AC uninstallation',
        description: 'Safe removal of split AC',
        price: 499,
        duration: '1.5 hrs',
        rating: 4.84,
        reviews: '1.7M',
        discount: null,
        tags: ['40 visits'],
        image: '/assets/ac.png',
        badge: null,
      },
      {
        id: 'window-ac-uninstallation',
        name: 'Window AC uninstallation',
        description: 'Professional window AC removal',
        price: 199,
        duration: '1 hr',
        rating: 4.88,
        reviews: '1M',
        discount: null,
        tags: [],
        image: '/assets/ac.png',
        badge: null,
      },
    ],
  },
  2: {
    // Grooming
    categoryName: 'Salon for Women',
    description: 'Professional beauty and grooming services at home',
    services: [
      {
        id: 'waxing-full-body',
        name: 'Full body waxing',
        description: 'Smooth skin with complete body waxing',
        price: 899,
        duration: '90 mins',
        rating: 4.85,
        reviews: '2.3M',
        discount: 'UP TO 20%',
        tags: ['Rica wax included', 'Pain-free waxing'],
        image: '/assets/grooming.png',
        badge: null,
      },
      {
        id: 'facial-gold',
        name: 'Gold facial',
        description: 'Luxury gold facial for glowing skin',
        price: 1299,
        duration: '60 mins',
        rating: 4.82,
        reviews: '1.5M',
        discount: null,
        tags: ['Anti-aging benefits', 'Instant glow'],
        image: '/assets/grooming.png',
        badge: 'TRENDING',
      },
      {
        id: 'hair-spa',
        name: 'Hair spa & treatment',
        description: 'Deep conditioning hair spa',
        price: 799,
        duration: '75 mins',
        rating: 4.79,
        reviews: '2.1M',
        discount: null,
        tags: ['Suitable for all hair types', 'Repair damaged hair'],
        image: '/assets/grooming.png',
        badge: null,
      },
      {
        id: 'pedicure-manicure',
        name: 'Pedicure & Manicure',
        description: 'Complete nail care and grooming',
        price: 599,
        duration: '60 mins',
        rating: 4.88,
        reviews: '3M',
        discount: null,
        tags: ['Nail polish included', 'Hand & foot massage'],
        image: '/assets/grooming.png',
        badge: null,
      },
      {
        id: 'hair-color',
        name: 'Hair color & highlights',
        description: 'Professional hair coloring service',
        price: 1499,
        duration: '120 mins',
        rating: 4.76,
        reviews: '1.2M',
        discount: 'UP TO 15%',
        tags: ['Ammonia-free colors', '100+ shades available'],
        image: '/assets/grooming.png',
        badge: null,
      },
      {
        id: 'bridal-makeup',
        name: 'Bridal makeup',
        description: 'Complete bridal makeover',
        price: 3999,
        duration: '180 mins',
        rating: 4.92,
        reviews: '850K',
        discount: null,
        tags: ['Includes trial', 'Premium products'],
        image: '/assets/grooming.png',
        badge: 'PREMIUM',
      },
    ],
  },
  3: {
    // Cleaning
    categoryName: 'Cleaning Services',
    description: 'Professional home and office cleaning',
    services: [
      {
        id: 'deep-cleaning',
        name: 'Deep home cleaning',
        description: 'Complete deep cleaning of your home',
        price: 1499,
        duration: '3-4 hrs',
        rating: 4.81,
        reviews: '2.5M',
        discount: 'UP TO 25%',
        tags: ['All rooms included', 'Kitchen & bathroom deep clean'],
        image: '/assets/cleaning.png',
        badge: 'MOST BOOKED',
      },
      {
        id: 'bathroom-cleaning',
        name: 'Bathroom cleaning',
        description: 'Thorough bathroom sanitization',
        price: 399,
        duration: '45 mins',
        rating: 4.75,
        reviews: '1.8M',
        discount: null,
        tags: ['Anti-bacterial cleaning', 'Includes all fixtures'],
        image: '/assets/cleaning.png',
        badge: null,
      },
      {
        id: 'kitchen-cleaning',
        name: 'Kitchen deep cleaning',
        description: 'Complete kitchen cleaning and degreasing',
        price: 799,
        duration: '90 mins',
        rating: 4.79,
        reviews: '1.6M',
        discount: null,
        tags: ['Chimney & stove cleaning', 'Cabinet cleaning'],
        image: '/assets/cleaning.png',
        badge: null,
      },
      {
        id: 'sofa-cleaning',
        name: 'Sofa & carpet cleaning',
        description: 'Deep cleaning for upholstery',
        price: 599,
        duration: '60 mins',
        rating: 4.83,
        reviews: '2M',
        discount: null,
        tags: ['Dry cleaning method', 'Stain removal'],
        image: '/assets/cleaning.png',
        badge: null,
      },
      {
        id: 'full-home-sanitization',
        name: 'Full home sanitization',
        description: 'Complete home disinfection service',
        price: 999,
        duration: '2 hrs',
        rating: 4.86,
        reviews: '1.3M',
        discount: null,
        tags: ['WHO approved chemicals', 'Safe for kids & pets'],
        image: '/assets/cleaning.png',
        badge: 'RECOMMENDED',
      },
      {
        id: 'move-in-cleaning',
        name: 'Move-in/out cleaning',
        description: 'Complete cleaning for moving',
        price: 1999,
        duration: '4-5 hrs',
        rating: 4.78,
        reviews: '900K',
        discount: null,
        tags: ['All rooms included', 'Window & balcony cleaning'],
        image: '/assets/cleaning.png',
        badge: null,
      },
    ],
  },
  4: {
    // Painting
    categoryName: 'Painting Services',
    description: 'Expert interior and exterior painting',
    services: [
      {
        id: 'interior-painting',
        name: 'Interior wall painting',
        description: 'Professional interior painting service',
        price: 1999,
        duration: '1-2 days',
        rating: 4.77,
        reviews: '1.4M',
        discount: 'UP TO 30%',
        tags: ['Premium paints', 'Free color consultation'],
        image: '/assets/painting.png',
        badge: null,
      },
      {
        id: 'exterior-painting',
        name: 'Exterior painting',
        description: 'Weather-resistant exterior painting',
        price: 2499,
        duration: '2-3 days',
        rating: 4.73,
        reviews: '850K',
        discount: null,
        tags: ['Weather proof paints', '5 year warranty'],
        image: '/assets/painting.png',
        badge: null,
      },
      {
        id: 'texture-painting',
        name: 'Texture painting',
        description: 'Designer texture painting',
        price: 3999,
        duration: '2-4 days',
        rating: 4.81,
        reviews: '600K',
        discount: null,
        tags: ['Multiple designs', 'Luxury finish'],
        image: '/assets/painting.png',
        badge: 'PREMIUM',
      },
      {
        id: 'waterproofing',
        name: 'Waterproofing service',
        description: 'Complete waterproofing solution',
        price: 4999,
        duration: '3-5 days',
        rating: 4.84,
        reviews: '700K',
        discount: null,
        tags: ['10 year warranty', 'Leakage protection'],
        image: '/assets/painting.png',
        badge: null,
      },
      {
        id: 'wood-polishing',
        name: 'Wood polishing',
        description: 'Furniture and door polishing',
        price: 1499,
        duration: '1 day',
        rating: 4.79,
        reviews: '1.1M',
        discount: null,
        tags: ['All wood types', 'Multiple finish options'],
        image: '/assets/painting.png',
        badge: null,
      },
    ],
  },
  5: {
    // Additional category - same as Grooming
    categoryName: 'Salon for Men',
    description: 'Professional grooming services for men',
    services: [
      {
        id: 'haircut-men',
        name: 'Haircut & styling',
        description: 'Professional haircut with styling',
        price: 299,
        duration: '30 mins',
        rating: 4.82,
        reviews: '2.8M',
        discount: null,
        tags: ['Includes head massage', 'Style consultation'],
        image: '/assets/grooming.png',
        badge: null,
      },
      {
        id: 'beard-trim',
        name: 'Beard trimming & shaping',
        description: 'Expert beard grooming',
        price: 199,
        duration: '20 mins',
        rating: 4.85,
        reviews: '2.2M',
        discount: null,
        tags: ['Precision trimming', 'Beard oil massage'],
        image: '/assets/grooming.png',
        badge: null,
      },
      {
        id: 'facial-men',
        name: "Men's facial",
        description: 'Deep cleansing facial for men',
        price: 799,
        duration: '45 mins',
        rating: 4.78,
        reviews: '1.5M',
        discount: 'UP TO 20%',
        tags: ['Suitable for all skin types', 'Anti-tan treatment'],
        image: '/assets/grooming.png',
        badge: null,
      },
    ],
  },
  6: {
    // Additional category - same as Cleaning
    categoryName: 'Office Cleaning',
    description: 'Commercial and office cleaning services',
    services: [
      {
        id: 'office-deep-clean',
        name: 'Office deep cleaning',
        description: 'Complete office sanitization',
        price: 2999,
        duration: '4-6 hrs',
        rating: 4.79,
        reviews: '1.2M',
        discount: null,
        tags: ['All areas covered', 'After hours service available'],
        image: '/assets/cleaning.png',
        badge: null,
      },
      {
        id: 'daily-office-cleaning',
        name: 'Daily office cleaning',
        description: 'Regular office maintenance',
        price: 1499,
        duration: '2-3 hrs',
        rating: 4.83,
        reviews: '980K',
        discount: 'UP TO 20%',
        tags: ['Flexible timing', 'Monthly packages available'],
        image: '/assets/cleaning.png',
        badge: 'POPULAR',
      },
    ],
  },
  allServices: {
    // For "More" button
    categoryName: 'All Services',
    description: 'Browse all our services',
    services: [], // Will combine all services
  },
};

// Helper function to get services by category ID
export const getServicesByCategory = (categoryId) => {
  if (categoryId === 'allServices') {
    // Combine all services from all categories
    const allServices = [];
    Object.keys(servicesData).forEach((key) => {
      if (key !== 'allServices') {
        allServices.push(...servicesData[key].services);
      }
    });
    return {
      categoryName: 'All Services',
      description: 'Browse all our services',
      services: allServices,
    };
  }

  return (
    servicesData[categoryId] || {
      categoryName: 'Services',
      description: '',
      services: [],
    }
  );
};

// Get category name by ID
export const getCategoryName = (categoryId) => {
  const categoryMap = {
    1: 'Repair',
    2: 'Grooming',
    3: 'Cleaning',
    4: 'Painting',
    5: 'Grooming',
    6: 'Cleaning',
    7: 'Painting',
    8: 'Plumbing',
    9: 'Plumbing',
    10: 'Plumbing',
    11: 'Plumbing',
    12: 'Electrician',
    allServices: 'All Services',
  };
  return categoryMap[categoryId] || 'Services';
};
